[package]
name = "griswell-sw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#sdl2_image = "0.25.0"

[dependencies.sdl2]
version = "0.36.0"
default-features = false
features = ["gfx", "image"]
